from enum import Enum, auto

class Phrases(Enum):
    START_MESSAGE = auto()
    HELP_MESSAGE = auto()
    CANCEL_MESSAGE = auto()
    WORD_NOT_FOUND = auto()
    NO_DEFINITIONS_FOUND = auto()
    UNKNOWN_ACTION = auto()
    ALL_DEFINITIONS = auto()
    MORE_DETAILS = auto()
    SYNONYMS = auto()
    ANTONYMS = auto()
    RHYMES = auto()
    CLOSE = auto()
    MAIN_MEANING = auto()
    INVALID_COMMAND_USAGE = auto()
    INVALID_LANGUAGE = auto()
    LANGUAGE_CHANGED = auto()
    COMMAND_RANDOM = auto()
    COMMAND_LANG_EN = auto()
    COMMAND_LANG_RU = auto()
    COMMAND_HELP = auto()